package org.tempuri;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-10T19:31:29.980+08:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "CruisesTravelerWebService",
                  wsdlLocation = "https://tpnet.twport.com.tw/HOPWS/WS/CruisesTravelerWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class CruisesTravelerWebService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://tempuri.org/", "CruisesTravelerWebService");
    public static final QName CruisesTravelerWebServiceSoap = new QName("http://tempuri.org/", "CruisesTravelerWebServiceSoap");
    public static final QName CruisesTravelerWebServiceSoap12 = new QName("http://tempuri.org/", "CruisesTravelerWebServiceSoap12");
    static {
        URL url = null;
        try {
            url = URI.create("https://tpnet.twport.com.tw/HOPWS/WS/CruisesTravelerWebService.asmx?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CruisesTravelerWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://tpnet.twport.com.tw/HOPWS/WS/CruisesTravelerWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CruisesTravelerWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CruisesTravelerWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CruisesTravelerWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CruisesTravelerWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CruisesTravelerWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CruisesTravelerWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CruisesTravelerWebServiceSoap
     */
    @WebEndpoint(name = "CruisesTravelerWebServiceSoap")
    public CruisesTravelerWebServiceSoap getCruisesTravelerWebServiceSoap() {
        return super.getPort(CruisesTravelerWebServiceSoap, CruisesTravelerWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CruisesTravelerWebServiceSoap
     */
    @WebEndpoint(name = "CruisesTravelerWebServiceSoap")
    public CruisesTravelerWebServiceSoap getCruisesTravelerWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(CruisesTravelerWebServiceSoap, CruisesTravelerWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns CruisesTravelerWebServiceSoap
     */
    @WebEndpoint(name = "CruisesTravelerWebServiceSoap12")
    public CruisesTravelerWebServiceSoap getCruisesTravelerWebServiceSoap12() {
        return super.getPort(CruisesTravelerWebServiceSoap12, CruisesTravelerWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CruisesTravelerWebServiceSoap
     */
    @WebEndpoint(name = "CruisesTravelerWebServiceSoap12")
    public CruisesTravelerWebServiceSoap getCruisesTravelerWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(CruisesTravelerWebServiceSoap12, CruisesTravelerWebServiceSoap.class, features);
    }

}
