package org.tempuri;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-10T19:31:29.883+08:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CruisesTravelerWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CruisesTravelerWebServiceSoap {

    @WebMethod(operationName = "GetExcel", action = "http://tempuri.org/GetExcel")
    @RequestWrapper(localName = "GetExcel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExcel")
    @ResponseWrapper(localName = "GetExcelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExcelResponse")
    @WebResult(name = "GetExcelResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.PSSApiResponse getExcel(

        @WebParam(name = "sDate", targetNamespace = "http://tempuri.org/")
        java.lang.String sDate,
        @WebParam(name = "eDate", targetNamespace = "http://tempuri.org/")
        java.lang.String eDate,
        @WebParam(name = "cruMode", targetNamespace = "http://tempuri.org/")
        java.lang.String cruMode,
        @WebParam(name = "shipType", targetNamespace = "http://tempuri.org/")
        java.lang.String shipType,
        @WebParam(name = "cruCate", targetNamespace = "http://tempuri.org/")
        java.lang.String cruCate,
        @WebParam(name = "vesType", targetNamespace = "http://tempuri.org/")
        java.lang.String vesType,
        @WebParam(name = "firstCru", targetNamespace = "http://tempuri.org/")
        java.lang.String firstCru,
        @WebParam(name = "dirRoute", targetNamespace = "http://tempuri.org/")
        java.lang.String dirRoute,
        @WebParam(name = "vesselCname", targetNamespace = "http://tempuri.org/")
        java.lang.String vesselCname,
        @WebParam(name = "vesselNo", targetNamespace = "http://tempuri.org/")
        java.lang.String vesselNo,
        @WebParam(name = "callSign", targetNamespace = "http://tempuri.org/")
        java.lang.String callSign,
        @WebParam(name = "port", targetNamespace = "http://tempuri.org/")
        java.lang.String port
    );
}
